[package]
name = "bresenham"
version = "0.1.0"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
license = "MIT"
description = "An fast, iterator-based integer-only implementation of Bresenham's line algorithm."

[dependencies]
